title:            Chris Yin
url:              http://chrisyin.com
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-35234352-1
timezone:         TIMEZONE
paginate: 5
links: 
  - name:         About
    url:          /about
  - name:         Quotes
    url:          /quotes
